modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="jackos_bossified_weapons_forge"
version="1.0.0"
displayName="Jacko's Bossified Weapons Forge"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="user, MCreator"

[[dependencies.jackos_bossified_weapons_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




